version: '3'
services:
  mysql_server:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_DATABASE: development
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  express_server:
    build: .
    depends_on:
      - mysql_server
    command: npm run docker_up
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    restart: always